version: '3.8'

services:
  mcp-host:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mcp-host
    ports:
      - "9000:9000"
    environment:
      - MCP_SERVER_URL=http://mcp-weather-server:9010
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - MCP_HOST_KAFKA_URL=kafka:9092
    restart: unless-stopped
    depends_on:
      - kafka
    networks:
      - mcp-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - mcp-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - mcp-network

networks:
  mcp-network:
    name: mcp-network
